### ISSUE TITLE
T2.0 commission withdrawal results in signature verification error with Ledger

### ISSUE THREAD

**Issue by m8nky** [stationmoney/station#102]
**Context**
Try to withdraw the validator commission with Terra station web (Ledger) fails.

```
signature verification failed; please verify account number (***), sequence (***) and chain-id (phoenix-1): unauthorized
```

**Steps to reproduce**
1. Connect Ledger with Terra station and open: https://station.terra.money/commission
2. Click Submit
3. Sign message on Ledger and confirm.

**Expected behavior**
Commission withdrawal succeeds.

**More info and further observations**
- Tried different browsers (Chrome, Brave).
- Other station interaction works, e.g. voting.
- When issuing the withdrawal with Terra CLI, it works...
  - though it uses a different withdrawal message: 'distribution.v1beta1.MsgWithdrawValidatorCommission'.
  - Terra station tries to sign a message of type: 'cosmos-sdk/MsgWithdrawValCommission' - which is reflected in Terra.js (https://github.com/terra-money/terra.js/blob/main/src/core/distribution/msgs/MsgWithdrawValidatorCommission.ts)
  - Not sure if this is related...

**Comment by m8nky** [comment]
Thank you @YunSuk-Yeo and @Vritra4 for the fix. Supposedly, this led to more errors.

Trying to sign the withdrawal immediately results in: 'Data is invalid : Unrecognized error code'

In addition, after reloading the page then, we get a react error: 'Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=n for the full message'

**Comment by simcheolhwan** [comment]
@m8nky I've never seen such a React error. On which page does such an error come out?

**Comment by m8nky** [comment]
Same, at /commission. Used Brave browser and it occurred after the first error and doing a reload of the page. After that, I really have to close and open the page again to get the platform working.

**Comment by simcheolhwan** [comment]
@m8nky Such a React error came out when user didn't connect with the validator account, and it is fixed.
I will check the "data invalid" error and comment here again.

**Comment by simcheolhwan** [comment]
@m8nky We found why this happens. This will be fixed soon.

**Comment by simcheolhwan** [comment]
@m8nky If the msg type is too long, the ledger cannot sign it.
We requested a pr to correct this, but the ledger team has not yet merged it. There's nothing we can do until they approve it.

As workaround, set a non-ledger address to withdraw using `MsgSetWithdrawAddr`.
