### ISSUE TITLE
Core tokens removed from station

### ISSUE THREAD

**Issue by DioAlma** [stationmoney/station#105]
Dinheiros, reis, escudos and alem have been removed from terra station.
This is a project I have been dedicating full time of my attention socially technically and personally.
I have been treating the markets with respect always selling and buying my own currency when in need of exchange, never withdrawing or playing with pool sizes since release.
I was immensely excited with the new release on station and the fact I was listed.
After noticing a bug happening in only one of the tokens, dinheiros, not being able to be bought even if it had more liquidity than the other 3 tokens(also not the first bug I report, and is validated from my side(I also identified a UI bug for the terraswap team that was fixed straight away), I like to be an engaged and respectful community member)
And as a reward of noticing a bug all my tokens were removed from the list!!!
This makes me and my investors very sad.
Will you please restore the tokens back on terra station? Or at least tell me how much liquidity I need to have to be relisted. (And it would be sad if you would have a liquidity minimum, specially in such a beginning stage where there are so little tokens this is an amazing opportunity from small devs that believed in the project from the begining and are dedicated to create great things, like my self)
Keep up the good work(other than this small bump)

Thank you, 
Diogo

**Comment by simcheolhwan** [comment]
Only pairs with $50k+ of liquidity are listed to the Station. The reason is to protect the users as you might expect. Of course you can also trade less liquid pairs by accessing tfm.com directly.

**Comment by DioAlma** [comment]
Good luck with that. What a lame excuse. I thought you guys were cool. I
was wrong. Migrating to classic. Bye bye
