### ISSUE TITLE
Apply optional burning tax to terra station rewards for LUNC

### ISSUE THREAD

**Issue by ZigZapps** [stationmoney/station#110]
**Summary**
Apply an optional burning tax on terra station staking rewards for LUNC upon withdrawal.

**Motivation**
This could drastically decrease the current supply of Terra Luna Classic which will help to put LUNC back on healthy levels and gain traction again amongst other major cryptocurrencies.

**Proposal**
Applying the optional burning tax on terra staking rewards can help to decrease the current circulating supply and potentially help the community to be self sufficient without the need to rely on the central exchanges to burn the extra tokens.

The implementation can be added on terra station when the user tries to withdraw the rewards. An optional box with numeric (decimal) field that can be applied before the withdrawal. Once the user withdraw the rewards, the optional burning tax will be calculated and subtracted from the total withdrawn rewards. i.e. total rewards = 10000, optional burning tax set = 50%, the total withdrawn lunc = 5000 and the rest will be burnt.

**Comment by thomasWos** [comment]
Is the 1,2% burning tax not already applied on staking reward withdrawal?

**Comment by ZigZapps** [comment]
> Is the 1,2% burning tax not already applied on staking reward withdrawal?

Nope
