### ISSUE TITLE
Staking UI tooltip and APR% calculations are wrong

### ISSUE THREAD

**Issue by kyjak** [stationmoney/station#112]
hello,
the tooltip on the APR states "Luna" where it should state "Luna classic" when switched to other network.
The Rewards number is WAY off reality. The estimator needs probably adjustements.
In the screenshot terra station claims 30 lunc on 100 lunc invested in 1 month return.
Real calculation is more 0.1 lunc on 100 lunc invested for 1 month return. This is very misleading for stakers.

![image](https://user-images.githubusercontent.com/15310250/193227720-b5d547cb-fddd-4460-8acb-552eb3e28688.png)

**Comment by alecande11** [comment]
Only for classic, and don't depend on Station but on api.terra.dev
