### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by tvl83** [stationmoney/station#12]
I am curious about the thought process behind requiring certain amount of staking for a color scheme. 

I would like to suggest to allow the Dark theme for free. 

Bringing new people into the eco system and the official wallet not allowing a dark theme unless they stake I think is very off putting. Some people simply cannot do that and a dark theme is pretty much a must for certain people.

**Comment by hanjukim** [comment]
Staking 1 Luna sounds not that hard and it is also good for the ecosystem.
