### ISSUE TITLE
Indicate whether the proposal is passing is calculated wrong

### ISSUE THREAD

**Issue by StrathCole** [stationmoney/station#129]
In commit f99cf176202cde2d8b5872855f7d1437090a64a3 there was the new "passing…" (the word, not the line) indicator introduced.

This seems to always calculate "Abstain" votes in favor of "Yes" votes, which does not reflect what the chain is doing.

The code responsible for this is in `src/pages/gov/ProposalVotes.tsx`
![Bildschirmfoto von 2022-11-25 22-13-11](https://user-images.githubusercontent.com/7449529/204056021-7a7df142-8577-44ea-a2b2-f40af0c72eda.png)

Lines
```
const consentRatio = list.slice(0, 2).map(({ ratio }) => ratio.byVoted)
const isPassing = !isBelowQuorum && BigNumber.sum(...consentRatio).gte(0.5)
```
simply seem to take the first two voting entries and adds them for the passing ratio, while abstain should count either not at all (which is what the chain itself does) or towards the third entry (no) if those votes are greater than "yes" votes (to display the indicator correctly).

**Comment by StrathCole** [comment]
In addition it seems that no with veto votes are not counted for the quorum threshold on the indicator.

**Comment by esoderquist** [comment]
@StrathCole - just submitted a PR that attempts to address this discrepancy and aligns the passing/not passing indicator with chain calculations documented at https://docs.terra.money/develop/module-specifications/spec-governance/#tallying. This includes honoring the veto_threshold. Awaiting TFL review...

**Comment by esoderquist** [comment]
It also proposes moving abstain votes to the final position of the progress bar to give the passing threshold flag meaning. This is how it looks on my dev instance (prop 10940):

![image](https://user-images.githubusercontent.com/9516403/204110191-713aa8c0-b706-42b1-b7e7-2422db474faa.png)

**Comment by StrathCole** [comment]
Thank you that looks much better.
