### ISSUE TITLE
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded

### ISSUE THREAD

**Issue by popcornazerty** [stationmoney/station#13]
Every time I try to access one of my wallet from "import private key" on terra station chrome app I get this error

Steps to reproduce:
Install terra station chrome app
import private key

Expected result:
Able to log in wallet
<img width="403" alt="Capture d’écran 2022-01-05 à 16 08 09" src="https://user-images.githubusercontent.com/78792807/148240344-dc7ca41f-986a-4464-8df5-9d0681f00075.png">

Sidenote: When creating a new wallet on Terra station OSX app, I was able to create a name of only 3 digits while trying to recover a wallet from terra station chrome app doesn't let you recover a wallet less than 5 alphanumeric numbers.

Terra station chrome app
<img width="406" alt="Capture d’écran 2022-01-05 à 16 11 11" src="https://user-images.githubusercontent.com/78792807/148240814-f4663af7-6cb1-4443-88d7-c9ad4ae9407b.png">

VS Terra station osx app
<img width="868" alt="Capture d’écran 2022-01-05 à 16 11 51" src="https://user-images.githubusercontent.com/78792807/148240925-446fa4b3-e430-4d80-b731-d10c28dfbc8e.png">

**Comment by simcheolhwan** [comment]
This error occurs when the pasted text is not in the correct format. Export key again and retry.

The minimum characters of wallet name is different, but it is not an issue. However, the extension will be updated next week.
