### ISSUE TITLE
Underlying cosmos api pagination.key functionality appears to skip items when paginating in reverse with count_total

### ISSUE THREAD

**Issue by esoderquist** [stationmoney/station#133]
Opening this issue rather than adding additional detail to PR #130. #130 improves the visibility of whitelisted items, and also introduces a client-side workaround for the underlying api issue. The workaround introduced by #130 should be retracted once the underlying api issue is identified/fixed to eliminate an extra api call each time the proposal status context (voting, deposit, passed, rejected) changes.

Initial issue described as:

Related to paging behavior - I believe I have uncovered an issue with the LCD/cosmos endpoint https://columbus-lcd.terra.dev/cosmos/gov/v1beta1/proposals. Specifically, requesting a reverse ordered set of paginated records works great for the first set, but when fetching the second set using the next page key, a record is skipped between returned sets. This only seems to occur if pagination.count_total=true is included on the initial call. I'll continue to research and will submit github issue/PR to the appropriate repo once I have an opportunity to review further.

Repro (note that this repro does not work as of 11/27 19:15 UTC as there are now 10 records - see theory below regarding issue only impacting datasets with odd number of total records):

Note the order of the first 9 proposals returned by https://columbus-lcd.terra.dev/cosmos/gov/v1beta1/proposals?proposal_status=2&pagination.limit=9&pagination.count_total=true&pagination.reverse=true
Fetch the first 3 records: https://columbus-lcd.terra.dev/cosmos/gov/v1beta1/proposals?proposal_status=2&pagination.limit=9&pagination.count_total=true&pagination.reverse=true
Fetch the next 3 records: https://columbus-lcd.terra.dev/cosmos/gov/v1beta1/proposals?proposal_status=2&pagination.limit=9&pagination.count_total=true&pagination.reverse=true&pagination.key=NEXTKEYFROMPREVCALL
Note that the second call above properly returns the most recent 3 records, along with the record total, but the subsequent paged call skips the 4th most recent record.

**Comment by esoderquist** [comment]
When this issue was initially discovered related to proposals in the voting status, there were 9 total proposals and the reproduction steps above highlighted the issue.

Now that there are 10 voting status proposals, the issue is not present. However, there are currently an odd number (105) of Passed proposals, and the issue as described above is present.

**Comment by esoderquist** [comment]
An update to #130 has been submitted on commit 1ac34b4 to work around the api-side issue while maintaining pagination functionality

**Comment by esoderquist** [comment]
Appears to be related to https://github.com/cosmos/cosmos-sdk/issues/11407, first merged in cosmos-sdk v0.46.0-alpha4

**Comment by alecande11** [comment]
Will be fixed with the interchain update
