### ISSUE TITLE
Why was ledger support removed from the desktop app?

### ISSUE THREAD

**Issue by orientalperil** [stationmoney/station#14]
Is there a reason why ledger stopped working in the desktop Terra Station app?  This was a very nice feature and it's gone now.  I prefer to use the desktop app with ledger.

**Comment by simcheolhwan** [comment]
Use https://station.terra.money to connect with ledger device please

**Comment by orientalperil** [comment]
@simcheolhwan I know that works.  I'm asking if you can explain why it was removed.  There is no explanation in the release notes, the docs, or in the git commits.  This matters because using the app is significantly worse now than it was before.

There are many obvious simple questions that need answers that are not written anywhere.

What is the actual reason?
Is this on purpose?
Are you deprecating the desktop app?
Should everyone stop using the desktop app?
Is it because of a library/security/coding issue?
Is this permanent?
Do you plan on adding this feature back in the future?

**Comment by mattdperkins** [comment]
I would love to know this as well and have seen multiple threads on reddit with people trying to find out why they cannot use the desktop app anymore.

**Comment by orientalperil** [comment]
@simcheolhwan Can you comment on this?

**Comment by simcheolhwan** [comment]
I understand you feel bad to be forced to use the Chrome browser.

But if the ledger users can interact with Terra core in any way, I think it is not blocking you to do something.

And if you use dapps like Anchor or Mirror or any other dapps, you should connect it to the Chrome extension.

In these days, Terra is not only for just core. It is for the contracts and the third-party dapps based on it.

So I ask you to use the browser.

**Comment by simcheolhwan** [comment]
Actually we are building another desktop app which is for the decentralized ecosystem. 

In this version, we will try to include the ledger support again.

**Comment by orientalperil** [comment]
It's actually not about my feelings.  I don't mind using chrome to use terra.

I don't really think you understand what I'm asking.  I'm asking why.

I'm just asking a really really simple question which you haven't answered.  Why was it removed?  What was the motivation?  There must be a reason you consciously chose to do it.

This is not written anywhere.  It's not in the release notes.  It's not in git commit messages.  It's not in the docs.  I've tried to read everything there is to find the answer and it is not available.  It is completely 100% unexplained.  This shouldn't be so hard for an open source project.

Can you just explain why?

**Comment by simcheolhwan** [comment]
To set the browser as default Terra Station, desktop app includes only thing that browser never can do.

**Comment by orientalperil** [comment]
This answer doesn't really make sense.  If that's the case then you should remove the ability of the desktop app to take a seed phrase because the browser extension can take a seed phrase.  If you actually did this that would mean the desktop app would do nothing and you should just deprecate the whole thing.

So in conclusion there is actually no real reason why you removed ledger support.    If you're intending to release a different desktop app anyway it would make more sense to release that before removing ledger support from the current version.  You should not remove basic features unless you have a real reason which in this case you do not.

**Comment by simcheolhwan** [comment]
If the desktop app was just deprecated, the users who used only desktop app but forgot their mnemonic cannot access their assets anymore.

Shall we stop this infinite conversation since this doesn't make any progress? I am sure that this will be just endless story without any productive result.

Thanks for your feedback. Good luck :)

**Comment by orientalperil** [comment]
> If the desktop app was just deprecated, the users who used only desktop app but forgot their mnemonic cannot access their assets anymore.

Yes that's the point.  That is the reason why your answer doesn't make sense.

> 
> Shall we stop this infinite conversation since this doesn't make any progress? I am sure that this will be just endless story without any productive result.

You think this only because you cannot see that your own answer is illogical.

**Comment by simcheolhwan** [comment]
You're right! I am illogical.

**Comment by simcheolhwan** [comment]
This conversation is locked because the maintainer of this repository defined it is not an issue anymore.
