### ISSUE TITLE
Only 100 Validators displaying on Stake Page for Classic Network

### ISSUE THREAD

**Issue by luncburnaus** [stationmoney/station#141]
Steps to reproduce:
1. Change Network to Classic
2. Click on Stake on the left Navigation
3. Under Validators, only 100 active validators are displayed

Expected:
130(if 130 bonded) active validators are displayed.

**Comment by luncburnaus** [comment]
My analysis shows the issue is with the LCD. The call to lcd https://terra-classic-lcd.publicnode.com/cosmos/staking/v1beta1/validators?status=BOND_STATUS_BONDED&pagination.limit=999 is ignoring the pagination.limit query parameter.

**Comment by alexandruast** [comment]
This is not fixed at the time of posting, despite @luncburnaus closing the issue.
![image](https://user-images.githubusercontent.com/12368572/206636507-a8e3a11e-e49e-40bb-9204-6890513da404.png)

**Comment by luncburnaus** [comment]
Thanks, @alexandruast. have reopened it. Can certainly see the issue is occurring again.
