### ISSUE TITLE
My wallet address changed

### ISSUE THREAD

**Issue by irishann69** [stationmoney/station#15]
Good day,

I have 2 concerns actually.

1. Just logged into today using my ledger device and I noted that my luna wallet address has changed, is this possible?
2. It appears that 10 days ago I received a message in my luna wallet to mint some NFT's, I didn't do this as I don't know what the source is. I did take note of the wallet address that the message appears to originate from, any information/awareness on this?

Would appreciate your kind assistance on these queries

Regards

Ann

**Comment by simcheolhwan** [comment]
1. It is not possible.
2. It's not happened from your wallet, someone sent you an NFT.

**Comment by irishann69** [comment]
You say it’s not possible!!!! It happened, my own wallet with my address is
now empty!!!!! All my Luna gone but they are in a new address!!!! Explain
this to me!!!!!!

**Comment by simcheolhwan** [comment]
@irishann69 Contact me please

Telegram: @simcheolhwan
