### ISSUE TITLE
Enable Cosmos app to access with ledger 

### ISSUE THREAD

**Issue by jaybxyz** [stationmoney/station#17]
Terra station used to allow (I think this is recently updated; it used to work) to access ledger with Cosmos app which provides a different address from the one using Terra app. It now returns the following message `Open the Terra app in the Ledger`. Is this intended? 

If it is, is there a way to use certain version of Terra station? because I have been accessing Terra station with Cosmos app since it is convenient to transfer UST from Osmosis app to Terra ecosystem back and forth using the same address. Now i can only access it using Terra app.

**Comment by simcheolhwan** [comment]
Terra Station supports only Terra ledger app.

**Comment by jaybxyz** [comment]
@simcheolhwan Any plan to provide users an option to choose which app (supposedly derivation path is different) to access or is there any workaround? Because the funds are stuck now in the Cosmos app. There seems to me other users who are struggling with this issue as well.

**Comment by simcheolhwan** [comment]
Try https://legacy.station.terra.money

**Comment by simcheolhwan** [comment]
No plan for Cosmos ledger app support

**Comment by jaybxyz** [comment]
Thanks for the legacy version of app. I found a workaround using this https://github.com/terra-money/station-legacy.
