### ISSUE TITLE
Cosmos App not supported anymore

### ISSUE THREAD

**Issue by brianmori** [stationmoney/station#19]
Hello,

I would like to report an issue. I have read many users used the Cosmos app with Ledger to connect to Terra Station.
This new release does not support the Cosmos app because it asks to Open the Terra app in the Ledger.

Many users has luna staked in astroport until November or December.

Would you be so kind to the issue?

I think the solution is to add the Keplr Derivation Path along with the Terra Station to allow retro-compatibility

**Comment by simcheolhwan** [comment]
Terra Station supports only Terra ledger app. (#17)

**Comment by apollo-sturdy** [comment]
> Terra Station supports only Terra ledger app. (#17)

No shit. Would be nice if you could please reply with why this support was removed. Unless there is a really good reason I would suggest reverting the removal of this support so that people can use IBC with Ledger, among other things.

**Comment by simcheolhwan** [comment]
There is no "really good" reason. We support only our official ledger app. That's it.

**Comment by apollo-sturdy** [comment]
> There is no "really good" reason. We support only our official ledger app. That's it.

You're still not answering the question though. What I'm asking is _why do you only support the terra ledger app_? It seems to me that there is no downside to allowing people to use the Cosmos app, and in fact many upsides, such as being able to use IBC with Ledger. If as you say there is no good reason not to allow people to use the Cosmos app, then why close the PR that re-introduced the support?
