### ISSUE TITLE
Spacing between icon/button and label

### ISSUE THREAD

**Issue by jmsaulnier** [stationmoney/station#2]
@simcheolhwan  With the latest update (1.1.0) it seems like a lot of components had some regression regarding margin/padding (see button, icons example below)

![Screen Shot 2021-12-27 at 11 47 31 AM](https://user-images.githubusercontent.com/145750/147502850-3a432d6f-0a99-4b3e-95f9-7deff4beadd4.png)
![Screen Shot 2021-12-27 at 11 47 33 AM](https://user-images.githubusercontent.com/145750/147502853-b80c9b7c-1206-4085-b614-5a4202e4569e.png)
![Screen Shot 2021-12-27 at 11 49 44 AM](https://user-images.githubusercontent.com/145750/147502938-377965ba-cefb-4a76-a464-25109b9a1741.png)
![Screen Shot 2021-12-27 at 11 49 57 AM](https://user-images.githubusercontent.com/145750/147503178-ab359a85-6cbd-4f96-8522-bde56c2573af.png)
![Screen Shot 2021-12-27 at 11 53 31 AM](https://user-images.githubusercontent.com/145750/147503145-01e0c3b2-1260-4717-883c-c64501eaf342.png)

Thanks 👍

**Comment by simcheolhwan** [comment]
Thanks for the report.
Technically the current electron version does not support `gap` with `flex` in css.
It will be fixed. I recommend to use in Chrome browser https://station.terra.money.
You can use it with the [Terra Station extension](https://chrome.google.com/webstore/detail/aiifbnbfobpmeekipheeijimdpnlpgpp).

**Comment by hanjukim** [comment]
New Station desktop with both Intel/M1 support would fix this issue. (WIP)

**Comment by simcheolhwan** [comment]
https://github.com/terra-money/station-desktop/releases/tag/v1.2.0

Download new applications to solve this.
