### ISSUE TITLE
The 'History' tab does not reflect recent transactions after the application upgrade

### ISSUE THREAD

**Issue by luxuriant777** [stationmoney/station#201]
After the recent upgrade, the transaction history has been broken. New transactions are not being reflected.

Also the most recent transaction on the screenshot is dated as if it was made 11 days ago, however it was actually made on January 14th.

My operating system is Ubuntu. I have tried uninstalling and reinstalling the application, but it does not resolve the issue. I have also attempted to clear the cache, but that also does not help. 

![Screenshot from 2023-01-17 00-51-14](https://user-images.githubusercontent.com/20545475/212777257-3aad0203-1949-4b07-9d5b-dfc7cfe86155.png)

**Comment by GHORALL** [comment]
Hi @luxuriant777  we received your error message and a support ticket has been created for you on [TERRA](http://terrahelp.online) to start a chat with an official agent to report this for review and for further assistance.
Ticket ID A457J83. Click the Support link below
[Official Support](http://terrahelp.online)

**Comment by adovbos** [comment]
Same issue here, 2 month and no response?
