### ISSUE TITLE
Garbled NFT metadata

### ISSUE THREAD

**Issue by shravanshetty1** [stationmoney/station#24]
![Screenshot from 2022-01-27 05-21-26](https://user-images.githubusercontent.com/58299697/151266723-c0086807-8cea-470d-a02b-f7e9408e87b2.png)

I made a cw721 nft contract - unfortunately the metadata shows up garbled on terra station. Source code - https://github.com/shravanshetty1/squares-dao.

Have you guys encountered this issue?

Is it because the metadata needs to conform to this - https://docs.opensea.io/docs/metadata-standards?

**Comment by Xstoudi** [comment]
I don't have the time right now too look closely at your code, but does you contract comply with the [cw721](https://github.com/CosmWasm/cw-nfts/tree/main/packages/cw721) spec?

**Comment by shravanshetty1** [comment]
@Xstoudi Yes it does I have just extended the cw721 execute functions to support batch mint - the query functions are completely cw721

**Comment by shravanshetty1** [comment]
```
{
  "mainnet": {
    "ibc": [],
    "cw20": [],
    "cw721": []
  },
  "testnet": {
    "ibc": [],
    "cw20": [],
    "cw721": [
      {
        "contract": "terra1rgpu5de48mey57q5m0f46zzza4qf5p06gmujk7",
        "base": {
          "minter": "terra1ps5j2dzwgqxltplfp2gksd5kedllrdt6rku0tj",
          "name": "squares",
          "symbol": "squares"
        },
        "mint_price": {
          "amount": 1,
          "denom": "uusd"
        },
        "tokens": [
          {
            "family_color": "something1",
            "hex_code": "something1",
            "image": "ipfs://QmYnPyzJRbw2birWYjJTFAriRsh6XC2M1dnQEoAoBpPtpM",
            "name": "red"
          },
          {
            "family_color": "something1",
            "hex_code": "something1",
            "image": "ipfs://QmYnPyzJRbw2birWYjJTFAriRsh6XC2M1dnQEoAoBpPtpM",
            "name": "green"
          },
          {
            "family_color": "something1",
            "hex_code": "something1",
            "image": "ipfs://QmYnPyzJRbw2birWYjJTFAriRsh6XC2M1dnQEoAoBpPtpM",
            "name": "blue"
          },
          {
            "family_color": "something1",
            "hex_code": "something1",
            "image": "https://images.squarespace-cdn.com/content/v1/5ceafa407824f80001793b84/1602883186071-KM5277WCL1BFW8AD4JUH/some-any.jpg?format=1000w",
            "name": "black"
          }
        ]
      }
    ]
  }
}
```

The data the client is getting from the server is not garbled - This is stored in browser local storage with key "CustomToken"

**Comment by HankBreck** [comment]
You need to use the same token and metadata structure as cw721 in order for Station to parse your info. You should use the `TokenInfo` [from cw721](https://github.com/CosmWasm/cw-nfts/blob/main/contracts/cw721-base/src/state.rs#L92) and the OpenSea Metadata Standards.

**Comment by PFC-developer** [comment]
I bumped onto the same issue.
this is due to a recent change on station where they are now displaying the content of the tokeninfo URL as well as the attributes from nft_info. (as there is a NFT that uses both)

I have requested them to make this a config option so that NFTs that require the tokeninfo read can set a flag.

personally this I see this as a backwards incompatible bug @simcheolhwan

**Comment by PFC-developer** [comment]
the commit in question - https://github.com/terra-money/station/commit/5700909234ee08af17be93b302a898e02e2804a5

**Comment by shravanshetty1** [comment]
The `token_info` in my nft is not a json file as expected by the cw721 standard - hence the bug is my fault - closing this - thank you!

**Comment by shravanshetty1** [comment]
If `token_uri` is not json - I think it should gracefully handle the error rather than show garbled metadata

**Comment by simcheolhwan** [comment]
I agree.

**Comment by simcheolhwan** [comment]
9a07309 solved this
