### ISSUE TITLE
Wallet address cannot be verified on Ledger Hardware Wallet via Terra Station web app

### ISSUE THREAD

**Issue by agsfbm6** [stationmoney/station#28]
When using Terra Station web app in Chrome paired with a USB Ledger device there is no option to verify the wallet address displayed in Terra Station on the Ledger hardware wallet display.

According to the tutorial:
https://medium.com/terra-money/how-to-use-ledger-nano-with-terra-station-dab33fc8aad5

> 6. Click Wallet on the menu in left panel, and you will see a Ledger icon next to your address. Click the icon. Once clicked, you should see your Terra address in your Ledger device. Please verify that the address shown in Station is the same on the device.

Obviously Terra Station layout changed and in the new layout there is no 'Ledger icon' to initiate the verification process.

I thus cannot trust / use the wallet address displayed on Terra Station without exposing myself to adversarial attacks (Terra Station code being manipulated).

**Comment by simcheolhwan** [comment]
Show ledger address on device feature will be added soon. Thanks for report.

**Comment by simcheolhwan** [comment]
4440867 resolved this
