### ISSUE TITLE
Governance vote colors

### ISSUE THREAD

**Issue by jmsaulnier** [stationmoney/station#3]
For new users, it might be difficult to understand these colors, maybe a label on hover is required to explain which category? 🤔  so we can have these colors, like part of the theme rather than having the same colors for all themes

![Screen Shot 2021-12-27 at 11 59 35 AM](https://user-images.githubusercontent.com/145750/147503458-5066d4be-618c-4e28-92ad-48160701a663.png)

Thanks 👍

**Comment by simcheolhwan** [comment]
Thank you for the suggestion. We will consider it.
I close this to track only critical bugs here.
