### ISSUE TITLE
Navigation - Current/hover items should have a more visible state

### ISSUE THREAD

**Issue by jmsaulnier** [stationmoney/station#4]
On hover, only label opacity is updating and selected is updating font to bold

![Screen Shot 2021-12-27 at 12 04 21 PM](https://user-images.githubusercontent.com/145750/147503748-4e86d071-20cf-4f7d-bf2c-aec0d0e5d6e5.png)

I think we should add a background hover/select state as well

See examples here https://tailwindui.com/components/application-ui/page-examples/home-screens

Thanks 👍

**Comment by simcheolhwan** [comment]
Thank you for the suggestion. We will consider it.
I close this to track only critical bugs here.
