### ISSUE TITLE
Exported with wrong password | Invalid Hex string

### ISSUE THREAD

**Issue by Umbranocturna** [stationmoney/station#41]
I was able to export my private key on terrastation using a 2 character password.  (Seems odd as the minimum size is 10)
Iam pretty sure that it is not the originral password.
I did change the password after that, and now the export private key gives me a string that is not accepted by terrastation (invalid hex string)
I also cant sign transactions anymore.

I did not keep my recovery phrase, so the funds inside are as good as lost, condsidering the broken export function.

I just wanted to inform you, that i was able to export with a wrong password and basically break the wallet in the progress.

**Comment by simcheolhwan** [comment]
Restore your wallet with mnemonic and try again.
If you need more help, send a message to @simcheolhwan on Telegram.
