### ISSUE TITLE
2 addresses with same seed

### ISSUE THREAD

**Issue by YoavPa** [stationmoney/station#42]
I tried to recover my wallet on another computer using terra station.
My seed generated a different wallet address with no balance or history of transactions
I used the same wallet name, same password and same seed. 
I am still connected on to my wallet on my phone and on my old computer

How can there be multiple wallet addresses with same seed?
If my seed does not allow me to recover my wallet on a new computer how can I trust Luna?

Very odd

**Comment by simcheolhwan** [comment]
No, you didn't use the same seed.
Or make sure you didn't change the `index` value when you create or restore the wallet.
