### ISSUE TITLE
[Feature Request] Implement a verified / whitelisted dApp mechanism

### ISSUE THREAD

**Issue by allisonChilton** [stationmoney/station#47]
Many users are being scammed these days. While ultimate responsibility should always fall on users using best practices and proper security measures being taken, the extension can help accidents from occurring. 

**Proposed feature(s):** 
This could take a form similar to:
1. Let users add whitelisted websites to the extension (similar to how CEX will allow you to whitelist particular addresses and block withdrawals to others). Bypassing this whitelist would require extra confirmation / warning to user.
2. Let various protocols implement a "verified" auth header to give extension knowledge the website is a known legitimate terra protocol (Especially TFL sponsored dApps such as Anchor) and communicate that to user with extra warnings if an application matches known protocols but didn't submit verification header
3. Implement a naughty list of known scam sites / contract addresses to warn users with extra confirmations to proceed at own risk

The list isn't comprehensive or prescriptive, it's just to give an idea of what I'm getting at.

**Comment by simcheolhwan** [comment]
I agree. We will try to protect the users. Thank you for the good idea.

**Comment by alecande11** [comment]
1 and 2 are probably not needed atm, due to the low activity.
3 has been implemented and will be rolled out with the interchain upgrade
https://github.com/terra-money/station-extension/commit/4c186dc97a3f4be8efcafb5bee4c8af459238312
