### ISSUE TITLE
It looks strange that this project is brand new

### ISSUE THREAD

**Issue by rafaelzimmermann** [stationmoney/station#5]
Why this project looks so fresh, and has only one start? Am I in the wrong place?

**Comment by tvl83** [comment]
I didn't realize that til you pointed it out. looks like they restarted the repo I guess. Just released an update. maybe they did it from the ground up or something? not sure.

**Comment by simcheolhwan** [comment]
This repository is rewritten from the scratch. 
One more reason is the previous version is used for both Station and extension. But it should be seperated now.
If you want to browse the codes of previous version, visit https://github.com/terra-money/station-legacy please.
@rafaelzimmermann @tvl83
