### ISSUE TITLE
Where are private keys generated?

### ISSUE THREAD

**Issue by NeoDaHacker** [stationmoney/station#51]
@simcheolhwan @hanjukim @rafaelzimmermann 
Hello since the desktop is just a webview/wrapper for https://station.terra.money/. What function is used in this project (**since this project is station.terra.money**) to generate private keys for the desktop app? Also since the desktop app uses  **station.terra.money** that means Terra (as a company) can in theory view/take users private keys? Because we as users can't be sure that Terra is serving **exactly this** open-source project on the web. I'd appreciate if anyone can clear up my confusions, after that you will have a new Luna investor and probably many more 💯

**Comment by rafaelzimmermann** [comment]
I am not a maintainer, just a small contributor.
But station has 3 options under connect

![image](https://user-images.githubusercontent.com/2369982/159251742-c62900b7-2366-435d-b725-33aa45654472.png)

The first is just to watch an address
The second you private key will be created and stored on the wallet you connect to via Wallet Connect
The third the keys will be stored on you ledger.

In short, it does not generate private keys and it does not have access to your private key.

**Comment by simcheolhwan** [comment]
We build and serve **exactly this repository**.
However, let's suppose that we don't so we can steal someone's private key.
Then we have to send the private key somewhere over the network. And since all networks can be easily monitored by the inspector, someone must have already discovered it.
Private keys should not be delivered over the network.

**Comment by NeoDaHacker** [comment]
@rafaelzimmermann thx, but what about the desktop app (as well as the chrome extension). It allows users to create a "New wallet": https://docs.terra.money/docs/learn/terra-station/download/terra-station-desktop.html#create-a-wallet. 
Do you know  the function that generate private keys? Because as @simcheolhwan said in this issue (https://github.com/terra-money/station/issues/50) `generateAddresses` is not used by the desktop app. So then how are private keys generated? If it's not happening on client side (the desktop app) that means some code in  https://station.terra.money/ (aka this repository) generates them. And that's what most/a lot of users do is: create "New wallet" - they generate normal addresses without Ledger or Connect Wallet. And what kind of other wallet people can connect to via Connect Wallet that is open-source? Much appreciated 👍

**Comment by simcheolhwan** [comment]
It happens on the client side.

Did you guess that after the mnemonic is delivered to our server, we will create a private key and send it back to the client? That's a very strange idea.

**Comment by NeoDaHacker** [comment]
@simcheolhwan that's not what I mean, the issue has nothing to do with your servers.. Do you mind showing me the function that generates private keys **in this project**. Because by "client side "you still mean  https://station.terra.money/.

**Comment by simcheolhwan** [comment]
https://github.com/terra-money/station/blob/main/src/auth/modules/create/NewWalletForm.tsx#L7

**Comment by simcheolhwan** [comment]
For details: https://github.com/terra-money/terra.js/blob/main/src/key/MnemonicKey.ts

**Comment by NeoDaHacker** [comment]
@simcheolhwan thx.. also why I can't create a "New wallet" when using the web (this project)? But when I download the the desktop app which uses https://station.terra.money/ as a webview I can? Why not just enable this option if I run this project on localhost:3000?

**Comment by simcheolhwan** [comment]
Because the environment variable "SANDBOX" is not set to true on the web browser.

**Comment by simcheolhwan** [comment]
It would be better if you read the code yourself first before ask.
Instead of continuing to explain the code one by one for you here. What do you think?

**Comment by NeoDaHacker** [comment]
@simcheolhwan What I think? I think that you should explain the code you've written to your users better. Even as a coder I ain't waisting my time reading someones code that is incable of exlaining it.. Your README doens't mension changing "SANDBOX"... and I'm forced to use "not as open-source" desktop app. Hope u understand where I'm coming from. Remember: you are a multi-billion dollar project... at least make it easy for people to run their wallets from open-source by spending some time to add some extra steps in README. Thx

**Comment by simcheolhwan** [comment]
If you don't want to waste time reading my code, just don't do it. I never forced you to do that.
I don't agree with your idea. If I had to write down the description of all the codes on README, README itself would be larger than the codes. However, I will make more comments on this part.

I would like to use the GitHub issues to raise bugs or function requests. This conversation will be closed.
If you don't understand anything after reading the code, please contact @simcheolhwan via Telegram.
