### ISSUE TITLE
Can't recover wallet build with Terra Station Chrome Extension

### ISSUE THREAD

**Issue by blair4444** [stationmoney/station#53]
I built a Terra Station wallet with the Chrome Extension and deposited 5000 UST into the wallet using a ledger nano S. At some point I deleted the wallet from the extension and now cannot recover it. When I use the same ledger it brings up a new address with no funds in it. I've tried rebuilding the wallet from the seed phrase but this doesn't work either - again, a new address with no funds. I also tried the XDEFI wallet. This wallet will bring up multiple addresses but none of them are the right one. I can clearly see my funds on the terra blockchain scanner but it is at the original address I cannot seem to regenerate. Can anyone help? I think others have had this problem.

**Comment by hanjukim** [comment]
As far as I know, I don't know of other cases. I suggest you to try other seed phrases if you have.

**Comment by blair4444** [comment]
There are some on this page: https://www.reddit.com/r/terraluna/comments/s1mi8n/how_to_fix_your_ledger_with_terrastation_extension/

**Comment by robiso50** [comment]
Hello @blair4444  , A support ticket has been opened for you with Support ticket number TB7847HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by lopezj19** [comment]
Hello @blair4444  , A support ticket has been opened for you with Support ticket number TB7840HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by lopezj19** [comment]
> I built a Terra Station wallet with the Chrome Extension and deposited 5000 UST into the wallet using a ledger nano S. At some point I deleted the wallet from the extension and now cannot recover it. When I use the same ledger it brings up a new address with no funds in it. I've tried rebuilding the wallet from the seed phrase but this doesn't work either - again, a new address with no funds. I also tried the XDEFI wallet. This wallet will bring up multiple addresses but none of them are the right one. I can clearly see my funds on the terra blockchain scanner but it is at the original address I cannot seem to regenerate. Can anyone help? I think others have had this problem.

Hello, A support ticket has been opened for you with Support ticket number TM39B. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by Watson199** [comment]
> I built a Terra Station wallet with the Chrome Extension and deposited 5000 UST into the wallet using a ledger nano S. At some point I deleted the wallet from the extension and now cannot recover it. When I use the same ledger it brings up a new address with no funds in it. I've tried rebuilding the wallet from the seed phrase but this doesn't work either - again, a new address with no funds. I also tried the XDEFI wallet. This wallet will bring up multiple addresses but none of them are the right one. I can clearly see my funds on the terra blockchain scanner but it is at the original address I cannot seem to regenerate. Can anyone help? I think others have had this problem.

Hello, A support ticket has been opened for you with Support ticket number TM7739. You should talk to an ANCHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)

**Comment by simcheolhwan** [comment]
Technically, that can't happen. We receive these reports occasionally, but many of them ended up acknowledging their misunderstanding.
Currently, there is nothing wrong with the Ledger, so there is no way we can officially support it.
