### ISSUE TITLE
Terra Station is not accepting decimals

### ISSUE THREAD

**Issue by araiczyk** [stationmoney/station#54]
I'm trying to make a transfer using decimals (comma in mi phone) and TS is not accepting them.
Here there's a video: https://twitter.com/araiczyk/status/1507474902252589065?s=20&t=G383VsTTPn2lsNeZQBJ2Jg

Also when I enter a memo I'm not able to see what I'm writing.

**Comment by hanjukim** [comment]
Isn't it comma?

**Comment by araiczyk** [comment]
> Isn't it comma?

Yes, it's a comma, the default decimal separator in my iPhone (spanish)

**Comment by robiso50** [comment]
Hello @araiczyk  , A support ticket has been opened for you with Support ticket number TB7846HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by lopezj19** [comment]
Hello @araiczyk  , A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by simcheolhwan** [comment]
We solved this. The code has already been created and is about to be distributed.
I'll let you know when it's deployed.

**Comment by simcheolhwan** [comment]
terra-money/station-mobile@a6f6cc2 solved this
