### ISSUE TITLE
Unable to add or display NFTs in Station when using LocalTerra 

### ISSUE THREAD

**Issue by octalmage** [stationmoney/station#57]
Working on some tutorials for minting NFTs using LocalTerra and it would be nice to be able to see these NFTs in Station. Currently I get a JavaScript error when I attempt to add the contract address: 

https://user-images.githubusercontent.com/142006/161113103-4aaac3c3-daf9-4bbb-8d1a-618a91b3eee9.mov

It appears to be due to localterra missing in the customTokens object: 

<img width="471" alt="Screen Shot 2022-03-31 at 12 16 48 PM" src="https://user-images.githubusercontent.com/142006/161113233-a967a559-e384-4fc0-a457-775694a23671.png">

Please let me know if you have any questions about how to replicate, thanks!

**Comment by lopezj19** [comment]
> Working on some tutorials for minting NFTs using LocalTerra and it would be nice to be able to see these NFTs in Station. Currently I get a JavaScript error when I attempt to add the contract address:
> 
>  Screen.Recording.2022-03-31.at.12.17.05.PM.mov 
> It appears to be due to localterra missing in the customTokens object:
> 
> <img alt="Screen Shot 2022-03-31 at 12 16 48 PM" width="471" src="https://user-images.githubusercontent.com/142006/161113233-a967a559-e384-4fc0-a457-775694a23671.png">
> 
> Please let me know if you have any questions about how to replicate, thanks!

Hello, A support ticket has been opened for you with Support ticket number TM187H9. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by Watson199** [comment]
> Working on some tutorials for minting NFTs using LocalTerra and it would be nice to be able to see these NFTs in Station. Currently I get a JavaScript error when I attempt to add the contract address:
> 
>  Screen.Recording.2022-03-31.at.12.17.05.PM.mov 
> It appears to be due to localterra missing in the customTokens object:
> 
> <img alt="Screen Shot 2022-03-31 at 12 16 48 PM" width="471" src="https://user-images.githubusercontent.com/142006/161113233-a967a559-e384-4fc0-a457-775694a23671.png">
> 
> Please let me know if you have any questions about how to replicate, thanks!

Hello, A support ticket has been opened for you with Support ticket number TM7639. You should talk to an ANCHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)

**Comment by simcheolhwan** [comment]
Yes, errors occur in networks other than the mainnet and testnet. I'll fix it quickly and let you know.

**Comment by simcheolhwan** [comment]
098d6d0 fixed this

**Comment by octalmage** [comment]
![](https://media4.giphy.com/media/YTbZzCkRQCEJa/giphy.gif?cid=7f156cbdvqqsrejw4qstogc7lsz7bqkf4ytrlnj0gif6tio5&rid=giphy.gif&ct=g)
