### ISSUE TITLE
Theme color - individual setting for different wallet

### ISSUE THREAD

**Issue by ivanfong01** [stationmoney/station#6]
Can we have an individual setting for different wallet?
I always prefer black theme but my other wallet have no luna staked, when I switch to it, it reset to basic theme
and i need to change it back everytime its quite troublesome

**Comment by simcheolhwan** [comment]
I understood. I will improve it.

**Comment by simcheolhwan** [comment]
6bbefdc solved this.

Actually it does not work exactly like what you said, but at least you will keep the dark mode.
