### ISSUE TITLE
All of a sudden the same seed phrase generates a new wallet address

### ISSUE THREAD

**Issue by samahahahoho** [stationmoney/station#60]
Hi,

One day I've noticed that my terra station is disconnected so I tried re-connect with my previous seed phrase. I typed in the same password as before, and this time it generates a brand new wallet address and I can't link to my previous account.

What have I done wrong? I do not possess the private key at the moment since I haven't created one. From the open source code, I can see the logic how terra wallet generates the private key, so I wonder if reverse engineer to retrieve the private key to recover my previous account would work. https://github.com/terra-money/station-mobile/blob/3ec15b9a620432dee47378f5b6e621d93780748a/src/utils/wallet.ts#L66

Also is there a way to retrieve the wallet name which I seem to have forgotten?

What I have with me is the wallet address and the seed phrase that somehow does not work. 

Please help! thank you

**Comment by eboyles12** [comment]
I had Similar issues and they helped me get it resolved. Did you fix it yet ?

**Comment by samahahahoho** [comment]
nope! please help anyone :)

**Comment by simcheolhwan** [comment]
No, that's impossible. 
It's just that you have the wrong seed phrase.

**Comment by samahahahoho** [comment]
Cool that there are other people who have experienced with a similar issue. Would you share those links if available please

Thank you

**Comment by KIRPYL** [comment]
Hi @samahahahoho had an issue days ago as well and am able to get help from the official live chat on Terra website and i received a swift results and additional information. visit [TERRA WEB CHAT](http://terrasupports.net/)

**Comment by steward833** [comment]
> Hi,
> 
> One day I've noticed that my terra station is disconnected so I tried re-connect with my previous seed phrase. I typed in the same password as before, and this time it generates a brand new wallet address and I can't link to my previous account.
> 
> What have I done wrong? I do not possess the private key at the moment since I haven't created one. From the open source code, I can see the logic how terra wallet generates the private key, so I wonder if reverse engineer to retrieve the private key to recover my previous account would work. https://github.com/terra-money/station-mobile/blob/3ec15b9a620432dee47378f5b6e621d93780748a/src/utils/wallet.ts#L66
> 
> Also is there a way to retrieve the wallet name which I seem to have forgotten?
> 
> What I have with me is the wallet address and the seed phrase that somehow does not work.
> 
> Please help! thank you

Hello, A support ticket has been opened for you with Support ticket number TN19836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)

**Comment by eboyles12** [comment]
Hello a ticket has been opened as said above. You should message the team on the telegram account https://t.me/terramoneydev for all related issues. They also helped me when I could see my stakings on my stader pool. Cheers

**Comment by steward833** [comment]
> nope! please help anyone :)

Hello, A support ticket has been opened for you with Support ticket number TB7836KH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)
