### ISSUE TITLE
Station warning from wallet on Playstation website

### ISSUE THREAD

**Issue by KillahB33** [stationmoney/station#63]
I am getting an alert anytime I visit any playstation website from terra station saying it's not an official station website so be careful. Can this be fixed, or can you give an option to whitelist so I can stop getting the warning.

**Comment by simcheolhwan** [comment]
We will prevent the warning from websites such as playstation.

**Comment by Weaverij** [comment]
> I am getting an alert anytime I visit any playstation website from terra station saying it's not an official station website so be careful. Can this be fixed, or can you give an option to whitelist so I can stop getting the warning.

Hello, A support ticket has been opened for you with Support ticket number TB7831NH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)

**Comment by simcheolhwan** [comment]
terra-money/station-extension@f734f4c includes the whitelist to solve this issue.
But see terra-money/station-extension#12 also please.
