### ISSUE TITLE
There seems to be something wrong with importing mixins

### ISSUE THREAD

**Issue by michaelessiet** [stationmoney/station#65]
All the sass files that have the
```sass
@import 'mixins'
```
statement say that the file doesn't exist. Am I missing something

**Comment by Weaverij** [comment]
> All the sass files that have the
> 
> ```sass
> @import 'mixins'
> ```
> 
> statement say that the file doesn't exist. Am I missing something

Hello, A support ticket has been opened for you with Support ticket number TB783MH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)
