### ISSUE TITLE
Delegate issue

### ISSUE THREAD

**Issue by 3sky** [stationmoney/station#68]
Hi,

I'm new to Terra ecosystem, so maybe I did something wrong. The goal is to bake some Lunas. 
In Terra Station Web I'm clicking -> 'Stake' -> 'stake.systems' -> `Delegate` -> In `Ammount` file I provided 1000.
Then the error appears: 
```javascript
failed to execute message; message index: 0: message type *types.MsgDelegate is not supported at height 7621088: message not supported: invalid request
``` 

Not sure if the issue is related to the ecosystem or to the app. `7621088` sounds like block height, so maybe it's related to the halt.

**Comment by hanjukim** [comment]
The function is disabled now.

**Comment by 3sky** [comment]
Thanks, @hanjukim. I wasn't sure about that, the error message is confusing 🙂 Is any plan to enable staking again in near future?

**Comment by hanjukim** [comment]
It is not going to be enabled in the current network. Thank you

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Terra Agent  LIVE SUPPORT [LIVE CHAT ](https://terra-supports.com/)
