### ISSUE TITLE
Send Luna Error due to insufficient fees

### ISSUE THREAD

**Issue by jimchang7** [stationmoney/station#69]
Terra Station (https://station.terra.money/send?token=uluna) is not using the right fee for sending Tx. The error message is:

`insufficient fees; got: "1267uluna", required: "21231uaud,21231ucad,15644uchf,109508ucny,100568udkk,13968ueur,12292ugbp,130739uhkd,243597560uidr,1215753uinr,1829217ujpy,18970440ukrw,633019uluna,47889381umnt,67046umyr,139678unok,849240uphp,11726usdr,139678usek,22349usgd,516249uthb,446968utwd,16762uusd" = "21231uaud,21231ucad,15644uchf,109508ucny,100568udkk,13968ueur,12292ugbp,130739uhkd,243597560uidr,1215753uinr,1829217ujpy,18970440ukrw,633019uluna,47889381umnt,67046umyr,139678unok,849240uphp,11726usdr,139678usek,22349usgd,516249uthb,446968utwd,16762uusd"(gas) +""(stability): insufficient fee`

<img width="982" alt="Screen Shot 2022-05-15 at 11 24 02 AM" src="https://user-images.githubusercontent.com/5591056/168455775-d1650a58-1ee8-4f5b-b5d7-cbdac5da7aa5.png">

**Comment by sammiyee** [comment]
> Terra Station (https://station.terra.money/send?token=uluna) is not using the right fee for sending Tx. The error message is:
> 
> `insufficient fees; got: "1267uluna", required: "21231uaud,21231ucad,15644uchf,109508ucny,100568udkk,13968ueur,12292ugbp,130739uhkd,243597560uidr,1215753uinr,1829217ujpy,18970440ukrw,633019uluna,47889381umnt,67046umyr,139678unok,849240uphp,11726usdr,139678usek,22349usgd,516249uthb,446968utwd,16762uusd" = "21231uaud,21231ucad,15644uchf,109508ucny,100568udkk,13968ueur,12292ugbp,130739uhkd,243597560uidr,1215753uinr,1829217ujpy,18970440ukrw,633019uluna,47889381umnt,67046umyr,139678unok,849240uphp,11726usdr,139678usek,22349usgd,516249uthb,446968utwd,16762uusd"(gas) +""(stability): insufficient fee`
> 
> <img alt="Screen Shot 2022-05-15 at 11 24 02 AM" width="982" src="https://user-images.githubusercontent.com/5591056/168455775-d1650a58-1ee8-4f5b-b5d7-cbdac5da7aa5.png">

Hello, A support ticket has been opened for you with Support ticket number MN378ET. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by SofosJ** [comment]
> Terra Station (https://station.terra.money/send?token=uluna) is not using the right fee for sending Tx. The error message is:
> 
> `insufficient fees; got: "1267uluna", required: "21231uaud,21231ucad,15644uchf,109508ucny,100568udkk,13968ueur,12292ugbp,130739uhkd,243597560uidr,1215753uinr,1829217ujpy,18970440ukrw,633019uluna,47889381umnt,67046umyr,139678unok,849240uphp,11726usdr,139678usek,22349usgd,516249uthb,446968utwd,16762uusd" = "21231uaud,21231ucad,15644uchf,109508ucny,100568udkk,13968ueur,12292ugbp,130739uhkd,243597560uidr,1215753uinr,1829217ujpy,18970440ukrw,633019uluna,47889381umnt,67046umyr,139678unok,849240uphp,11726usdr,139678usek,22349usgd,516249uthb,446968utwd,16762uusd"(gas) +""(stability): insufficient fee`
> 
> <img alt="Screen Shot 2022-05-15 at 11 24 02 AM" width="982" src="https://user-images.githubusercontent.com/5591056/168455775-d1650a58-1ee8-4f5b-b5d7-cbdac5da7aa5.png">

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by SofosJ** [comment]
> Terra Station (https://station.terra.money/send?token=uluna) is not using the right fee for sending Tx. The error message is:
> 
> `insufficient fees; got: "1267uluna", required: "21231uaud,21231ucad,15644uchf,109508ucny,100568udkk,13968ueur,12292ugbp,130739uhkd,243597560uidr,1215753uinr,1829217ujpy,18970440ukrw,633019uluna,47889381umnt,67046umyr,139678unok,849240uphp,11726usdr,139678usek,22349usgd,516249uthb,446968utwd,16762uusd" = "21231uaud,21231ucad,15644uchf,109508ucny,100568udkk,13968ueur,12292ugbp,130739uhkd,243597560uidr,1215753uinr,1829217ujpy,18970440ukrw,633019uluna,47889381umnt,67046umyr,139678unok,849240uphp,11726usdr,139678usek,22349usgd,516249uthb,446968utwd,16762uusd"(gas) +""(stability): insufficient fee`
> 
> <img alt="Screen Shot 2022-05-15 at 11 24 02 AM" width="982" src="https://user-images.githubusercontent.com/5591056/168455775-d1650a58-1ee8-4f5b-b5d7-cbdac5da7aa5.png">

Hello, A support ticket has been opened for you with Support ticket number BN2784MA. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by ornato-t** [comment]
Having the same issue with LUNC. If it might help, I am using a ledger device.

**Comment by icetrust0212** [comment]
I have the same issue with classic.
Anyone can help?
