### ISSUE TITLE
Issue starting development server

### ISSUE THREAD

**Issue by a-zb** [stationmoney/station#7]
Followed instructions.

node -v
v14.15.5

npm -v
6.14.11

Error:
====

npm run start

> terra-station@ start F:\Code\GitHub\station
> react-scripts start

i ｢wds｣: Project is running at https://192.168.1.12/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from F:\Code\GitHub\station\public
i ｢wds｣: 404s will fallback to /
Starting the development server...
Failed to compile.

./src/app/components/HeaderIconButton.module.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-7-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-7-4!./src/app/components/HeaderIconButton.module.scss)
SassError: Can't find stylesheet to import.
  ╷
1 │ @import "mixins";
  │         ^^^^^^^^
  ╵
  src\app\components\HeaderIconButton.module.scss 1:9  root stylesheet

**Comment by simcheolhwan** [comment]
Would you retry after setting the `SASS_PATH=./node_modules;./src/styles` inside your `.env` file?

**Comment by a-zb** [comment]
That worked. Excellent.
