### ISSUE TITLE
Transaction to Terra Station = Founds lost

### ISSUE THREAD

**Issue by buthus** [stationmoney/station#76]
Hi, sorry for that. I did a send:
https://finder.terra.money/classic/tx/E0B0C47DC1E2305C65A5B79664D60746CB2290D80AE214EA28DD1C4BF015CDE4

From Terra Station (with Terra Bridge Classic) and the founds don't be visible on my account...

Can you help me ?

**Comment by Gideon20222** [comment]
> Hi, sorry for that. I did a send: https://finder.terra.money/classic/tx/E0B0C47DC1E2305C65A5B79664D60746CB2290D80AE214EA28DD1C4BF015CDE4
> 
> From Terra Station (with Terra Bridge Classic) and the founds don't be visible on my account...
> 
> Can you help me ?

It sounds like your query would be best dealt with by the support team. I’ll have to refer you to the official support live chat with the ticket ID LUN76384
Please see the link below to our dedicated support line:
*  [Support: Terra Ecosystem Support](http://Terramoneysupport.com)
