### ISSUE TITLE
Governance vote changes are not reflected on station

### ISSUE THREAD

**Issue by etienne-napoleone** [stationmoney/station#82]
When a validator changes his vote (by sending a new one) for a given proposal, it doesn't update on Station.

For example, [proposal 349](https://station.terra.money/proposal/349) has Setten voting "Yes" while the latest vote was `VOTE_OPTION_ABSTAIN`.

First vote: [`VOTE_OPTION_YES`](https://finder.terra.money/mainnet/tx/D873363C7D104F5F607EA82AD66088CA28E841CBA75D2912C1225C2422BB441C)
Second vote: [`VOTE_OPTION_ABSTAIN`](https://finder.terra.money/mainnet/tx/076F60BCA8EC06400109EDFDB70A7C8220571867FF9D2924EB22CEB45CA7726F)

The second one overrides the first one.

**Comment by hanjukim** [comment]
~I think it's an cache issue?~

I think it's an API issue: https://phoenix-api.terra.dev/proposals/349 returns VOTE_OPTION_YES cc: @jeffwoooo

**Comment by hanjukim** [comment]
It's fixed now. api server was not responding to proposal changes due to websocket issue
