### ISSUE TITLE
[BUG] some validator can't do re-delegations

### ISSUE THREAD

**Issue by Livekus** [stationmoney/station#97]
Describe the bug
some validators can't do re delegations

To Reproduce
click stake -> choose a validator choose re-delegation ->choose PFC-OSS , Orbital Command ,Terra Bites , 01node, or LUNC DAO

Context & versions
Android (App version v2.0.0-161)and web

log :failed to execute message; message index: 0: too few tokens to redelegate (truncates to zero tokens): invalid request

**Comment by edk208** [comment]
a fix is proposed here, https://github.com/terra-money/station/pull/98
